---
spring:
  config:
    activate:
      on-profile: dev, default
  application:
    name: order-service
  threads:
    virtual:
      enabled: true
  cache.type: redis
  redis.host: localhost
  redis.port: 6379
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "password"
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:order_db}
    hikari.maximum-pool-size: 50
    hikari.minimum-idle: 10
    hikari.idle-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  logging:
    level:
      org:
        springframework: info
      root: info
    file:
      max-size: 10MB
      max-history: 10
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    path: ./public/logs/dev/@project.artifactId@-@project.version@

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: order-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "password"
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:order_db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  logging:
    level:
      org:
        springframework: info
      root: info
    file:
      max-size: 10MB
      max-history: 10
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    path: ./public/logs/dev/@project.artifactId@-@project.version@